name: example_project
description: Example Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.7.0
  get_storage: ^2.1.1
  connectivity_plus: ^6.0.5
  another_flushbar: ^1.12.30
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
    - assets/audio/

  fonts:
    - family: IRANSansWeb
      fonts:
        - asset: assets/fonts/IRANSansWeb(FaNum)_UltraLight.ttf
          weight: 200
        - asset: assets/fonts/IRANSansWeb(FaNum)_Light.ttf
          weight: 300
        - asset: assets/fonts/IRANSansWeb(FaNum).ttf
          weight: 400
        - asset: assets/fonts/IRANSansWeb(FaNum)_Medium.ttf
          weight: 500
        - asset: assets/fonts/IRANSansWeb(FaNum)_Bold.ttf
          weight: 700